""" country groups vocabularies """

COUNTRY_GROUPS = {
    ('CA5', 'Central Asia'): [
        u'Kyrgyzstan',
        u'Kazakhstan',
        u'Tajikistan',
        u'Turkmenistan',
        u'Uzbekistan'
    ],

    ('EN7', 'Eastern neighbours'): [
        u'Armenia',
        u'Azerbaijan',
        u'Belarus',
        u'Georgia',
        u'Moldova',
        u'Russian Federation',
        u'Ukraine'
    ],

    ('EFTA4', 'European Free Trade Association'): [
      u'Switzerland', u'Iceland', u'Liechtenstein', u'Norway'
    ],

    ('EU', 'European Union'): [
        u'Cyprus',
        u'Portugal',
        u'Spain',
        u'Malta',
        u'Denmark',
        u'United Kingdom',
        u'Sweden',
        u'Netherlands',
        u'Austria',
        u'Belgium',
        u'Germany',
        u'Luxembourg',
        u'Ireland',
        u'France',
        u'Slovakia',
        u'Czech Republic',
        u'Italy',
        u'Slovenia',
        u'Greece',
        u'Croatia',
        u'Estonia',
        u'Latvia',
        u'Lithuania',
        u'Finland',
        u'Hungary',
        u'Bulgaria',
        u'Poland',
        u'Romania'
    ],

    ('EU12', 'EU12'): [
        u'Belgium',
        u'Denmark',
        u'France',
        u'Germany',
        u'Greece',
        u'Ireland',
        u'Italy',
        u'Luxembourg',
        u'Netherlands',
        u'Portugal',
        u'Spain',
        u'United Kingdom',
    ],

    ('EU15', 'EU15'): [
         u'Portugal',
         u'Spain',
         u'Denmark',
         u'United Kingdom',
         u'Sweden',
         u'Netherlands',
         u'Austria',
         u'Belgium',
         u'Germany',
         u'Luxembourg',
         u'Ireland',
         u'France',
         u'Italy',
         u'Greece',
         u'Finland'
    ],

    ('EU25', 'EU25'): [
        u'Cyprus',
        u'Portugal',
        u'Spain',
        u'Malta',
        u'Denmark',
        u'United Kingdom',
        u'Sweden',
        u'Netherlands',
        u'Austria',
        u'Belgium',
        u'Germany',
        u'Luxembourg',
        u'Ireland',
        u'France',
        u'Slovakia',
        u'Czech Republic',
        u'Italy',
        u'Slovenia',
        u'Greece',
        u'Estonia',
        u'Latvia',
        u'Lithuania',
        u'Finland',
        u'Hungary',
        u'Poland'
    ],

    ('EU27', 'EU27'): [
        u'Cyprus',
        u'Portugal',
        u'Spain',
        u'Malta',
        u'Denmark',
        u'United Kingdom',
        u'Sweden',
        u'Netherlands',
        u'Austria',
        u'Belgium',
        u'Germany',
        u'Luxembourg',
        u'Ireland',
        u'France',
        u'Slovakia',
        u'Czech Republic',
        u'Italy',
        u'Slovenia',
        u'Greece',
        u'Estonia',
        u'Latvia',
        u'Lithuania',
        u'Finland',
        u'Hungary',
        u'Bulgaria',
        u'Poland',
        u'Romania'
    ],

    ('EU28', 'EU28'): [
        u'Cyprus',
        u'Portugal',
        u'Spain',
        u'Malta',
        u'Denmark',
        u'United Kingdom',
        u'Sweden',
        u'Netherlands',
        u'Austria',
        u'Belgium',
        u'Germany',
        u'Luxembourg',
        u'Ireland',
        u'France',
        u'Slovakia',
        u'Czech Republic',
        u'Italy',
        u'Slovenia',
        u'Greece',
        u'Croatia',
        u'Estonia',
        u'Latvia',
        u'Lithuania',
        u'Finland',
        u'Hungary',
        u'Bulgaria',
        u'Poland',
        u'Romania'
    ],

    ('EUN22', 'EU neighbours and their neighbours'): [
        u'Armenia',
        u'Azerbaijan',
        u'Belarus',
        u'Algeria',
        u'Egypt',
        u'Georgia',
        u'Israel',
        u'Jordan',
        u'Kyrgyzstan',
        u'Kazakhstan',
        u'Lebanon',
        u'Libya',
        u'Morocco',
        u'Moldova',
        u'Palestine',
        u'Russian Federation',
        u'Syria',
        u'Tajikistan',
        u'Turkmenistan',
        u'Tunisia',
        u'Ukraine',
        u'Uzbekistan'
    ],

    ('EEA', 'EEA Members'): [
        u'Austria',
        u'Belgium',
        u'Bulgaria',
        u'Croatia',
        u'Czech Republic',
        u'Cyprus',
        u'Denmark',
        u'Estonia',
        u'Finland',
        u'France',
        u'Germany',
        u'Greece',
        u'Hungary',
        u'Iceland',
        u'Ireland',
        u'Italy',
        u'Liechtenstein',
        u'Latvia',
        u'Lithuania',
        u'Luxembourg',
        u'Malta',
        u'Netherlands',
        u'Norway',
        u'Poland',
        u'Portugal',
        u'Romania',
        u'Slovakia',
        u'Slovenia',
        u'Spain',
        u'Sweden',
        u'Switzerland',
        u'United Kingdom',
        u'Turkey'
    ],

    ('EEA32', 'EEA-32 Members'): [
        u'Austria',
        u'Belgium',
        u'Bulgaria',
        u'Czech Republic',
        u'Cyprus',
        u'Denmark',
        u'Estonia',
        u'Finland',
        u'France',
        u'Germany',
        u'Greece',
        u'Hungary',
        u'Iceland',
        u'Ireland',
        u'Italy',
        u'Liechtenstein',
        u'Latvia',
        u'Lithuania',
        u'Luxembourg',
        u'Malta',
        u'Netherlands',
        u'Norway',
        u'Poland',
        u'Portugal',
        u'Romania',
        u'Slovakia',
        u'Slovenia',
        u'Spain',
        u'Sweden',
        u'Switzerland',
        u'United Kingdom',
        u'Turkey',
    ],

    ('EEA33', 'EEA-33 Members'): [
        u'Austria',
        u'Belgium',
        u'Bulgaria',
        u'Croatia',
        u'Czech Republic',
        u'Cyprus',
        u'Denmark',
        u'Estonia',
        u'Finland',
        u'France',
        u'Germany',
        u'Greece',
        u'Hungary',
        u'Iceland',
        u'Ireland',
        u'Italy',
        u'Liechtenstein',
        u'Latvia',
        u'Lithuania',
        u'Luxembourg',
        u'Malta',
        u'Netherlands',
        u'Norway',
        u'Poland',
        u'Portugal',
        u'Romania',
        u'Slovakia',
        u'Slovenia',
        u'Spain',
        u'Sweden',
        u'Switzerland',
        u'United Kingdom',
        u'Turkey',
    ],

    ('EIONET', 'Eionet'): [
        u'Albania',
        u'Austria',
        u'Bosnia and Herzegovina',
        u'Belgium',
        u'Bulgaria',
        u'Croatia',
        u'Czech Republic',
        u'Cyprus',
        u'Denmark',
        u'Estonia',
        u'Finland',
        u'France',
        u'Germany',
        u'Greece',
        u'Hungary',
        u'Iceland',
        u'Ireland',
        u'Italy',
        u'Liechtenstein',
        u'Latvia',
        u'Lithuania',
        u'Luxembourg',
        u'Malta',
        u'Montenegro',
        u'Netherlands',
        u'Norway',
        u'Poland',
        u'Portugal',
        u'Romania',
        u'Serbia',
        u'Slovakia',
        u'Slovenia',
        u'Spain',
        u'Sweden',
        u'Switzerland',
        u'United Kingdom',
        u'Turkey',
        u'Former Yugoslav Republic of Macedonia, the',
    ],

    ('NMS10', 'New Member States (10 countries)'): [
        u'Cyprus',
        u'Czech Republic',
        u'Estonia',
        u'Hungary',
        u'Lithuania',
        u'Latvia',
        u'Malta',
        u'Poland',
        u'Slovenia',
        u'Slovakia'
    ],

    ('NMS12', 'New Member States (12 countries)'): [
        u'Bulgaria',
        u'Cyprus',
        u'Czech Republic',
        u'Estonia',
        u'Hungary',
        u'Lithuania',
        u'Latvia',
        u'Malta',
        u'Poland',
        u'Romania',
        u'Slovenia',
        u'Slovakia'
    ],

    ('NMS13', 'New Member States (13 countries)'): [
        u'Bulgaria',
        u'Croatia',
        u'Cyprus',
        u'Czech Republic',
        u'Estonia',
        u'Hungary',
        u'Lithuania',
        u'Latvia',
        u'Malta',
        u'Poland',
        u'Romania',
        u'Slovenia',
        u'Slovakia'
    ],

    ('SN10', 'Southern neighbours'): [
        u'Algeria',
        u'Egypt',
        u'Israel',
        u'Jordan',
        u'Lebanon',
        u'Libya',
        u'Morocco',
        u'Palestine',
        u'Syria',
        u'Tunisia'
    ],

    ('WB6', 'West Balkan 6'): [
        u'Albania',
        u'Bosnia and Herzegovina',
        u'Croatia',
        u'Montenegro',
        u'Former Yugoslav Republic of Macedonia, the',
        u'Serbia'
    ],

    ('WB7', 'West Balkan 7'): [
        u'Albania',
        u'Bosnia and Herzegovina',
        u'Croatia',
        u'Montenegro',
        u'Kosovo (UNSCR 1244/99)',
        u'Former Yugoslav Republic of Macedonia, the',
        u'Serbia'
    ],

    ('YU', 'Former republics of Yugoslavia'): [
        u'Bosnia and Herzegovina',
        u'Croatia',
        u'Montenegro',
        u'Former Yugoslav Republic of Macedonia, the',
        u'Serbia',
        u'Slovenia',
        u'Kosovo (UNSCR 1244/99)'

    ]
}
